// src/views/Home.vue
<template>
  <div class="home">
    <div class="center">
      <figure class="image is-128x128 center">
        <img class="is-rounded" src="https://avatars2.githubusercontent.com/u/7285926?s=460&v=4">
      </figure>
      <p class="title is-1">Julian Beck</p>
      <p class="subtitle is-4">Computer Science Student</p>
      <p>Intrested in full Stack development & languages</p>
    </div>
    <a class="button is-medium" target="_blank" rel="noopener noreferrer" href="https://github.com/jufabeck2202">
      <span class="icon">
        <font-awesome-icon :icon="['fab', 'github']"/>
      </span>
      <span>GitHub</span>
    </a>
    <a class="button is-medium" target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/kickbeak/">
      <span class="icon is-medium">
        <font-awesome-icon :icon="['fab', 'instagram']"/>
      </span>
      <span>Instagram</span>
    </a>
    <a  class="button is-medium" target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/julian-beck/">
      <span class="icon is-medium">
        <font-awesome-icon :icon="['fab', 'linkedin']"/>
      </span>
      <span>linkedin</span>
    </a>
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from "@/components/HelloWorld.vue";

export default {
  name: "home",
  components: {
    HelloWorld
  }
};
</script>
<style>
.center {
  margin: auto;
  width: 50%;
}
</style>

// src/scenes/Home/Home.jsx
import React, { Component } from "react";
import { Grid, Image, Icon, Container, Header } from "semantic-ui-react";
import "./Home.css";


export default class Home extends Component {
  render() {
    return (
      <div style={{ paddingTop: "4em" }} >
        <Image
          src="https://avatars2.githubusercontent.com/u/7285926?s=460&v=4"
          centered
          size="small"
          circular
        />


        <Container textAlign="center">
          <Header style={{ paddingTop: "0.5em", marginBottom: 0, fontSize: "2.5rem" }} as='h1'>Julian Beck</Header>
          <p style={{ fontSize: "1.5rem", marginBottom: "0.1em" }}> Computer Science Student</p>
          <p style={{ fontSize: "1rem" }}> Intrested in full Stack development & languages</p>


          <Grid centered style={{marginTop: "0.1em" }} >
            <a style={{ color: "inherit" }} href="https://google.com">
              <Icon size="big" name="github" />Code</a>
            <a style={{ color: "inherit" }} href="https://google.com">
              <Icon size="big" name="linkedin" />linkedIn</a>
            <a style={{ color: "inherit" }} href="https://google.com">
              <Icon size="big" name="twitter" />Tweets</a>
          </Grid>
        </Container>
      </div>
    )
  }
}
