// pages/contact/index.vue
<template>
  <div class="contact container">
    <form method="POST" action="https://formspree.io/Kickbeck@googlemail.com">
      <div class="field">
        <label class="label">Name</label>
        <div class="control">
          <input class="input" type="text" name="your name" placeholder="Your Name">
        </div>
      </div>

      <div class="field">
        <label class="label">Email</label>
        <div class="control">
          <input
            class="input is-success"
            type="email"
            name="_replyto"
            placeholder="your email"
            value
          >
        </div>
      </div>

      <div class="field">
        <label class="label">Message</label>
        <div class="control">
          <textarea class="textarea" placeholder="Your message" name="message"></textarea>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <button type="submit" class="button is-link" value="Send">Submit</button>
        </div>
      </div>
    </form>
  </div>
</template>

// src/scenes/Contact/Contact.jsx
import React, { Component } from "react";
import { Form, Button,Header } from "semantic-ui-react";

export default class Contact extends Component {
  render() {
    return (
      <div style={{ paddingTop: "4em" }} className="contact" >
        <Header size="huge">Contact me</Header>
        <Form method="POST" action="https://formspree.io/Kickbeck@googlemail.com">
          <Form.Field>
            <label>Email</label>
            <input required type="email" name="email" placeholder="Your email" />
          </Form.Field>
          <Form.Field>
            <Form.TextArea required label='Message' name="message" className="message" placeholder='your Message' />
          </Form.Field>
          <Button type='submit'>Submit</Button>
        </Form>
      </div>
    )
  }
}
